Controllers/ReleaseReturnController.cs
using ASPNETWebApp48.Models;
using ASPNETWebApp48.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using X.PagedList;

namespace ASPNETWebApp48.Controllers
{
    [Authorize]
    public class ReleaseReturnController : Controller
    {
        InventoryDbContext _db = new InventoryDbContext();
        public ActionResult Manage()
        {
            if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
            {
                var returns = _db.ReleaseReturns
                    .Include(x => x.Releasing)
                    .Include(x => x.ReleaseReturnItems)
                    .OrderByDescending(x => x.Id)
                    .ToList();

                // Retrieve purchase IDs that are already in receiving
                var purchaseIdsInReceiving = _db.ReleaseReturns.Select(r => r.ReleaseId).ToList();

                var availableReturns = _db.Releasings
                    .Include(x => x.ReleaseItems) // Include the purchase items if needed
                    .Where(p => p.ReleaseItems.Sum(pi => pi.Quantity) >= 5 && !purchaseIdsInReceiving.Contains(p.Id))
                    .ToList();

                ViewBag.ReturnDate = DateTime.Now;
                ViewBag.ForCreatePartial = new Dictionary<string, object>
                {
                    { "ReleaseLookup", availableReturns }
                };

                return View(returns);
            }
            else if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
                ViewBag.Message = "releaser manager can access releasing return";

            return View();
        }

        [HttpPost]
        public ActionResult Create(ReleaseReturn returns)
        {
            var purchase = _db.Purchases
                .Include(p => p.Supplier)
                .FirstOrDefault(p => p.Id == returns.ReleaseId);

            string username = Session["user"] as string;
            LogActivity(username, "Release Return", "Create");
            _db.ReleaseReturns.Add(returns);
            _db.SaveChanges();
            return RedirectToAction("Get", new { Id = returns.Id });
        }

        public ActionResult Get(int Id) // Order.Id
        {
            if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
            {
                var returns = _db.ReleaseReturns
                    .Where(x => x.Id == Id)
                    .Include(x => x.Releasing)
                    .Include(x => x.ReleaseReturnItems)
                    .SingleOrDefault();

                var prod = _db.Products.ToList();

                // Get the PurchaseId from the returns entry
                var purchaseId = returns.ReleaseId;

                // Fetch the PurchaseItems associated with the specific PurchaseId and include the Product data
                var items = _db.ReleaseItems
                    .Where(pi => pi.ReleaseId == purchaseId)
                    .Include(pi => pi.Product)
                    .ToList();

                // Preparing the ViewBag data
                ViewBag.ForAddItemPartial = new Dictionary<string, object>
                {
                    { "ProductLookup", items },
                    { "ReturnId", returns.Id }
                };

                return View(returns);
            }
            else if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
                ViewBag.Message = "Purchase manager can access purchase return";

            return View();
        }

        //public ActionResult GetProductPrice(int Id) // Product.Id
        //{
        //    var unitPrice = _db.ReleaseItems.Find(Id).SellingPrice;
        //    return Json(unitPrice, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItem(ReleaseReturnItem returnDamage)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the corresponding order items for the product ID
                var orderItems = _db.ReleaseItems.Where(x => x.ProductId == returnDamage.ProductId).ToList();
                int totalQuantity = orderItems.Sum(x => x.Quantity);

                // Check if the quantity being returned is valid
                if (returnDamage.Quantity <= totalQuantity)
                {
                    _db.ReleaseReturnItems.Add(returnDamage);
                    string username = Session["user"] as string;
                    LogActivity(username, "Releasing Return", "Add Item");
                    TempData["alertbox"] = "Release Damage has been successfully added.";
                    _db.SaveChanges();  // Save changes for returnDamages
                }
                else
                    TempData["alertbox"] = "Return quantity exceeds the total quantity in orders.";
            }
            else
                TempData["alertcard"] = "There are some validation errors. Please check and try again.";

            return RedirectToAction("Get", new { Id = returnDamage.Id });
        }

        public ActionResult DelItem(int id)
        {
            var orderItem = _db.ReleaseReturnItems.Find(id);
            if (orderItem != null)
            {
                string username = Session["user"] as string;
                LogActivity(username, "Releasing Return", "Delete Item");
                _db.ReleaseReturnItems.Remove(orderItem);
                _db.SaveChanges();
            }

            return RedirectToAction("Get", new { Id = orderItem.ReturnId });
        }

        public ActionResult Cancel()
        {
            // Retrieve order item IDs from the session, if available
            List<int> orderItemIds = Session["orderItemIds"] as List<int>;

            if (orderItemIds != null && orderItemIds.Any())
            {
                foreach (int itemId in orderItemIds)
                {
                    var orderItem = _db.ReleaseReturnItems.Find(itemId);
                    if (orderItem != null)
                    {
                        _db.ReleaseReturnItems.Remove(orderItem);
                    }
                }

                string username = Session["user"] as string;
                LogActivity(username, "Releasing Return", "Cancel");
                Session.Remove("orderItemIds");
                _db.SaveChanges();
                TempData["alertbox"] = "Releasing return canceled." + Session["orderItemIds"];
            }
            else
                TempData["alertbox"] = "There are no adjustment item to cancel." + Session["orderItemIds"];

            return RedirectToAction("Manage");
        }

        [HttpPost]
        public ActionResult EditDetail(ReleaseReturn updatedOrder)
        {
            if (ModelState.IsValid)
            {
                if (Session["orderItemIds"] != null)
                {
                    // If orderItemIds exist in the session, log the activity
                    string username = Session["user"] as string;
                    LogActivity(username, "Releasing Return", "Edit Detail");
                    _db.Entry(updatedOrder).State = EntityState.Modified;
                    _db.SaveChanges();
                }
                else
                {
                    // If orderItemIds do not exist in the session, update the order status
                    string username = Session["user"] as string;
                    LogActivity(username, "Releasing Return", "Edit Detail");
                    _db.Entry(updatedOrder).State = EntityState.Modified;
                    _db.SaveChanges();
                }
                Session.Remove("orderItemIds");
                TempData["alertbox"] = "Releasing return changes have been successfully saved.";
            }
            else
                TempData["alertcard"] = "There are some validation errors. Please check and try again.";

            return RedirectToAction("Manage", new { Id = updatedOrder.Id });
        }

        public ActionResult ManageApproval()
        {
            if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
            {
                // Retrieve receiving data
                var returns = _db.ReleaseReturns
                    .Include(x => x.Releasing)
                    .Where(x => x.Status == "Pending")
                    .Include(x => x.ReleaseReturnItems)
                    .OrderByDescending(x => x.Id)
                    .ToList();

                ViewBag.ApproveDate = DateTime.Now; //for date
                ViewBag.RejectDate = DateTime.Now; //for date

                return View(returns);
            }
            else if (User.IsInRole("purchmgr") || User.IsInRole("wrhmgr"))
                ViewBag.Message = "releaser manager can access return approval";

            return View();
        }

        public ActionResult Detail(int Id) //for invoice detail
        {
            if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
            {
                var returns = _db.ReleaseReturns
                    .Include(x => x.Releasing)
                    .Where(x => x.Id == Id)
                    .SingleOrDefault();

                if (returns == null)
                {
                    TempData["alertbox"] = "Releasing Not Exist";
                    return RedirectToAction("Manage");
                }

                return View(returns);
            }
            else if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
                ViewBag.Message = "releaser can access invoice detail of releasing";

            return View();
        }

        public ActionResult Print(int Id) //for pdf
        {
            // Find the order with the specified Id along with its associated OrderItemWalkIns
            var order = _db.ReleaseReturns
                .Where(x => x.Id == Id)
                .Include(x => x.ReleaseReturnItems)
                .Include(x => x.Releasing)
                .SingleOrDefault();

Views/ReleaseReturn/Create.cshtml
@*@model ASPNETWebApp48.ViewModels.StockViewModel*@

@if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
{
    ViewBag.Title = "Create Releasing Return";

<div class="container-fluid">
    <div class="col-12 col-md-8 text-center">
        <h2>@ViewBag.Title</h2>
    </div>
    <form action="/ReleaseReturn/Create" method="post" enctype="multipart/form-data" class="form-horizontal mt-3">
        @Html.AntiForgeryToken()
        <div class="form-group row">
            <label class="col-sm-2 col-form-label text-center zoom-3">Customer</label>
            <div class="col-sm-5">
                <select id="ReleaseId" name="ReleaseId" class="form-control zoom-3" autofocus>
                    <option value="" selected disabled>Select Releasing Customer</option>
                    @foreach (var order in ViewBag.Order)
                    {
                        <option value="@order.Id">@order.LastName, @order.FirstName</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label text-center zoom-3">Product</label>
            <div class="col-sm-6">
                <select id="ProductId" name="ProductId" class="form-control text-center zoom-3" autofocus required></select>
            </div>
        </div>
        <div class="form-group row">
            <label for="Quantity" class="col-sm-2 col-form-label text-center zoom-3">Quantity</label>
            <div class="col-sm-10">
                <input id="Quantity" name="Quantity" type="text" class="form-control zoom-3" min="1" value="1" pattern="[0-9]+" title="Only numbers allowed" required>
                <input id="ReturnDate" name="ReturnDate" type="hidden" value="@ViewBag.ReturnDate.ToString("yyyy-MM-dd")">
            </div>
        </div>
        <div class="form-group row">
            <label for="Purpose" class="col-sm-2 col-form-label text-center zoom-3">Purpose</label>
            <div class="col-sm-10">
                <select id="Purpose" name="Purpose" class="form-control" required="required">
                    @*<option selected disabled value="">Select Purpose</option>*@
                    @*<option value="Overstock">Overstock</option>*@
                    <option selected value="Damage">Damage</option>                    
                    @*<option value="Dispose">Dispose</option>
                    <option value="Repair">Repair</option>*@
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2"></label>
            <div class="col-4">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                <a href="/ReleaseReturn/Manage" class="btn btn-secondary btn-lg">Cancel</a>
            </div>
        </div>
    </form>
</div>

    @section Scripts{
        <script>
        $(document).ready(function () {
            $('#ReleaseId').on('change', function () {
                var orId = $('#ReleaseId option:selected').val(); // Corrected to get selected value
                $.ajax({
                    type: 'GET',
                    data: { orId: orId },
                    url: '@Url.Action("LoadItems", "ReleaseReturn")',
                    success: function (result) {
                        var p = '<option value="" selected disabled>Select Product</option>';
                        var uniqueProducts = {}; // Object to store unique products
                        for (var i = 0; i < result.length; i++) {
                            var productId = result[i].ProductId;
                            var productName = result[i].Product;
                            if (!uniqueProducts[productId]) {
                                uniqueProducts[productId] = productName;
                                p += '<option value="' + productId + '">' + productName + '</option>';
                            }
                        }
                        $('#ProductId').html(p);
                    }
                });
            });
        });
        </script>
    }

    <link rel="stylesheet" href="/Content/Util/slimselect.min.css" />
    <script type="module">
        import SlimSelect from '/Scripts/Util/slimselect.es.min.js'
        new SlimSelect({
            select: '#ReleaseId',
            settings: { searchPlaceholder: 'Search for the Release!' }
        });
    </script>
}

Views/ReleaseReturn/CreateDamage.cshtml
@if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
{
    ViewBag.Title = "Create Releasing Damage";

    <div class="container-fluid">
        <div class="col-12 col-md-8 text-center">
            <h2>@ViewBag.Title</h2>
            <form action="/ReleaseReturn/CreateDamage" method="post" enctype="multipart/form-data" class="form-horizontal mt-3">
                @Html.AntiForgeryToken()
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-center zoom-3">Customer</label>
                    <div class="col-sm-5">
                        <select id="ReleaseId" name="ReleaseId" class="form-control zoom-3" autofocus>
                            <option value="" selected disabled>Select Releasing Customer</option>
                            @foreach (var order in ViewBag.Order)
                            {
                                <option value="@order.ReleaseId">@order.Releasing.LastName, @order.Releasing.FirstName</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-center zoom-3">Product</label>
                    <div class="col-sm-6">
                        <select id="ProductId" name="ProductId" class="form-control text-center zoom-3" autofocus required>
                            <option value="" selected disabled>Select Product</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Quantity" class="col-sm-2 col-form-label text-center zoom-3">Quantity</label>
                    <div class="col-sm-10">
                        <input id="Quantity" name="Quantity" type="number" class="form-control zoom-3" min="1" value="1" pattern="[0-9]+" title="Only numbers allowed" required>
                        <input id="ReturnDate" name="ReturnDate" type="hidden" value="@ViewBag.ReturnDate.ToString("yyyy-MM-dd")">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2"></label>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                        <a href="/ReleaseReturn/ManageDamage" class="btn btn-secondary btn-lg">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $('#ReleaseId').on('change', function () {
                    var orId = $('#ReleaseId option:selected').val();
                    console.log('Selected ReleaseId:', orId);
                    $.ajax({
                        type: 'GET',
                        data: { orId: orId },
                        url: '@Url.Action("LoadItems2", "ReleaseReturn")',
                        success: function (result) {
                            console.log('AJAX Success:', result);
                            var p = '<option value="" selected disabled>Select Product</option>';
                            var uniqueProducts = {}; // Object to store unique products
                            for (var i = 0; i < result.length; i++) {
                                var productId = result[i].ProductId;
                                var productName = result[i].Product;
                                var quantity = result[i].Quantity;
                                if (!uniqueProducts[productId]) {
                                    uniqueProducts[productId] = productName;
                                    p += '<option value="' + productId + '">' + productName + ' (Quantity: ' + quantity + ')</option>';
                                }
                            }
                            $('#ProductId').html(p);
                        },
                        error: function (xhr, status, error) {
                            console.error('AJAX Error:', status, error);
                            $('#ProductId').html('<option value="" selected disabled>Error Loading Products</option>');
                        }
                    });
                });
            });
        </script>
    }

    <link rel="stylesheet" href="/Content/Util/slimselect.min.css" />
    <script type="module">
        import SlimSelect from '/Scripts/Util/slimselect.es.min.js'
        new SlimSelect({
            select: '#ReleaseId',
            settings: { searchPlaceholder: 'Search for the Release!' }
        });
    </script>
}

Views/ReleaseReturn/Detail.cshtml
@model ASPNETWebApp48.Models.ReleaseReturn

@if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
{
    ViewBag.Title = "Invoice Detail | " + Model.Releasing.ClientName;

    <div class="main-panel">
        <div class="content-wrapper">
            <center>
                <br />
                <h3>JIMAR CONSTRUCTION SUPPLY CO., LTD.</h3>
                111-113 Gomez St. Cagayan De Oro City<br />
                Tel. Nos. (08822) 72-60-25, 72-31-44, 72-32-96 Fax 72-38-84
                <br /><br /><h3>Release Return Detail</h3>
                <p>
                    <hr />Release # : @Model.Id
                    <hr />Name : @Model.Releasing.ClientName
                    <hr />Date : @Model.ReturnDate.ToString("yyyy-MM-dd")
                    <hr />Status : @Model.Status
                    <hr />Reason : @Model.Reason<hr />
                </p>
                <a href="/ReleaseReturn/Print/@Model.Id"><input type="button" class="btn btn-info btn-lg" value="Print"></a>&nbsp;
                <a href="/ReleaseReturn/ManageApproval"><input type="button" class="btn btn-secondary btn-lg" value="Back to Manage"></a>
            </center>
        </div>
    </div>
}

Views/ReleaseReturn/Edit.cshtml
@model ASPNETWebApp48.Models.Return

@if (User.IsInRole("invmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
{
    ViewBag.Title = "Edit Return - " + Model.Order.LastName + " " + Model.Order.FirstName;

    <div class="container-fluid">
        <div class="col-8 text-center">
            <h2>@ViewBag.Title</h2><br />
        </div>
        <form action="/Return/Edit" method="post" enctype="multipart/form-data" class="form-horizontal mt-3">
            @Html.AntiForgeryToken()
            <!-- Text input-->
            <div class="form-group row">
                <label for="OrderId" class="col-sm-2 col-form-label text-center zoom-3">Customer:</label>
                <div class="col-sm-6">
                    <input id="Id" name="Id" type="hidden" value="@Model.Id" class="form-control">
                    <select id="OrderId" name="OrderId" class="form-control zoom-3" required>
                        <option value="@Model.OrderId" selected>Selected Order: @Model.Order.LastName,@Model.Order.FirstName</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="ReturnDate" class="col-sm-2 col-form-label text-center zoom-3">Return Date:</label>
                <div class="col-sm-10">
                    <input id="ReturnDate" name="ReturnDate" type="date" value="@Model.ReturnDate.ToString("yyyy-MM-dd")" readonly class="form-control zoom-3">
                </div>
            </div>
            <div class="form-group row">
                <label for="ProductId" class="col-sm-2 col-form-label text-center zoom-3">Product:</label>
                <div class="col-sm-6">
                    <select id="ProductId" name="ProductId" class="form-control text-center zoom-3" required>
                        <option value="@Model.ProductId" selected>@Model.Product.Name</option>
                        @foreach (var product in ViewBag.products)
                        {
                            <option value="@product.Id">@product.Name</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="Quantity" class="col-sm-2 col-form-label text-center zoom-3">Quantity:</label>
                <div class="col-sm-10">
                    <input id="Quantity" name="Quantity" type="number" value="@Model.Quantity" class="form-control zoom-3" min="1" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="Reason" class="col-sm-2 col-form-label text-center zoom-3">Reason:</label>
                <div class="col-sm-10">
                    <select id="Reason" name="Reason" class="custom-select" required="required">
                        <option selected value="@Model.Reason">@Model.Reason</option>
                        <option value="Add to stock">Add to stock</option>
                        <option value="Dispose">Dispose</option>
                        <option value="Repair">Repair</option>
                        <option value="Damage">Damage</option>
                    </select>
                </div>
            </div>
            <!-- Button -->
            <div class="form-group row">
                <label class="col-sm-2"></label>
                <div class="col-4">
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    <a href="/Return/Manage" class="btn btn-secondary btn-lg">Cancel</a>
                </div>
            </div>
        </form>
    </div>
}

Views/ReleaseReturn/Get.cshtml
@model ASPNETWebApp48.Models.ReleaseReturn
@using System.Globalization

@if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("salesmgr") || User.IsInRole("admin"))
{
    ViewBag.Title = "Edit Releasing Return - " + Model.Releasing.ClientName;

    <div class="container-fluid">
        <div class="card" style="margin-bottom: 20px">
            <div class="card-body">
                <h2 class="text-center">@ViewBag.Title</h2><hr />
                <form method="POST" action="/ReleaseReturn/EditDetail">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-md-2">
                            <div class="mb-2">
                                <label for="SupplierId">Supplier</label>
                                <input type="hidden" name="Id" value="@Model.Id" id="Id">
                                <input type="hidden" name="ReleaseId" value="@Model.ReleaseId" id="ReleaseId">
                                <input type="hidden" name="Status" value="@Model.Status" id="Status">
                                <input type="text" class="form-control" value="@Model.Releasing.ClientName" readonly>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="mb-2">
                                <label for="ReturnDate">Return Date</label>
                                <input type="text" name="ReturnDate" class="form-control" value="@Model.ReturnDate.ToString("yyyy-MM-dd")" id="ReturnDate" readonly>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <label for="Reason" class="col-4 col-form-label">Reason</label>
                            <textarea id="Reason" name="Reason" cols="40" rows="4" class="form-control">@Model.Reason</textarea>
                        </div>
                        <div class="col-md-3">
                            <div class="mb-2">
                                <center>
                                    <br />
                                    <button name="submit" type="submit" class="btn btn-primary btn-md">Save</button>
                                    <a href="/ReleaseReturn/Cancel" class="btn btn-secondary btn-md">Cancel</a>
                                </center>
                            </div>
                        </div>
                    </div>
                </form>
                <br /><h3 class="text-center">Returned Items</h3>
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap table-bordered table-sm">
                        <thead class="thead-light">
                            <tr>
                                <th class="text-center">Action</th>
                                <th class="text-center">Product</th>
                                <th class="text-center">Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var groupedItems = Model.ReleaseReturnItems.GroupBy(pi => pi.ProductId);
                            }

                            @foreach (var group in groupedItems)
                            {
                                var firstItem = group.First();
                                CultureInfo culture = new CultureInfo("en-PH");
                                <tr>
                                    <td class="text-center">
                                        <a href="/ReleaseReturn/DelItem/@firstItem.Id" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')" title="Delete" style="height: 25px;line-height: 1.0;">&times;</a>
                                    </td>
                                    <td class="text-center">@firstItem.Product.Name</td>
                                    <td class="text-center">@group.Sum(pi => pi.Quantity)</td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td class="text-center">
                                    @Html.Partial("_AddItem", ViewBag.ForAddItemPartial as Dictionary<string, object>)
                                </td>
                                <td colspan="2"></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

Views/ReleaseReturn/Manage.cshtml
@model List<ASPNETWebApp48.Models.ReleaseReturn>

@if (User.IsInRole("wrhmgr") || User.IsInRole("purchmgr"))
{
    <h3 class="text-center">@ViewBag.Message</h3>
}

@if (User.IsInRole("admin") || User.IsInRole("salesmgr"))
{
    ViewBag.Title = "Manage Releasing Return";

    <div class="container-fluid">
        <p class="float-right">
            <a class="btn btn-warning" href="/ReleaseReturn/ManageApproval">Approval</a>
            @Html.Partial("_Create", ViewBag.ForCreatePartial as Dictionary<string, object>)
        </p>
        <h2 class="text-center">@ViewBag.Title</h2>
        <div class="table-responsive">
            <table class="table table-hover text-nowrap table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th class="text-center">Client Name</th>
                        <th class="text-center">Return Date</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Reason</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var returns in Model)
                    {
                        <tr>
                            <td class="text-center">@returns.Releasing.ClientName</td>
                            <td class="text-center">@returns.ReturnDate.ToString("dd-MMM-yyyy")</td>
                            <td class="text-center">@returns.Status</td>
                            <td class="text-center">@returns.Reason</td>
                            <td class="text-center">
                                @if (returns.Status.Contains("Pending"))
                                {
                                    <a class="btn btn-warning btn-sm" href="/ReleaseReturn/Get/@returns.Id">Edit</a>
                                }
                                @if (returns.Status.Contains("Approve") || returns.Status.Contains("Reject"))
                                {
                                    <a href="/ReleaseReturn/Print/@returns.Id"><input type="button" class="btn btn-info btn-sm" value="Print"></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}